version: '3.8'

services:  
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-api
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8090:8090"
    depends_on:
      - chroma
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge